# Generated by Django 4.2.13 on 2026-05-31 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Actif'), ('expired', 'Expiré'), ('terminated', 'Résilié')], default='draft', max_length=20)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('platform_fee_percent', models.DecimalField(decimal_places=2, default=2, max_digits=5)),
                ('agent_commission', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commission_paid', models.BooleanField(default=False)),
                ('commission_before_rent', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('min_duration_months', models.IntegerField(default=1)),
                ('payment_day', models.IntegerField(default=1)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='contracts/leases/')),
                ('signed_by_tenant', models.BooleanField(default=False)),
                ('signed_by_owner', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('renewal_notified', models.BooleanField(default=False)),
                ('renewal_notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, limit_choices_to={'role': 'agent'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_contracts', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='landlord_contracts', to=settings.AUTH_USER_MODEL)),
                ('rental_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_contracts', to='properties.property')),
                ('tenant', models.ForeignKey(limit_choices_to={'role__in': ['client', 'tenant']}, on_delete=django.db.models.deletion.CASCADE, related_name='lease_contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bail',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentOwnerContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('expired', 'Expiré'), ('terminated', 'Résilié')], default='active', max_length=20)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('terms', models.TextField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='contracts/agent_owner/')),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signed_by_agent', models.BooleanField(default=False)),
                ('signed_by_owner', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(limit_choices_to={'role': 'agent'}, on_delete=django.db.models.deletion.CASCADE, related_name='agent_contracts', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='owner_contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contrat Agent-Propriétaire',
                'ordering': ['-created_at'],
            },
        ),
    ]
