# Generated by Django 4.2.13 on 2026-06-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentownercontract',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contrat Agent-Proprietaire'},
        ),
        migrations.AlterField(
            model_name='agentownercontract',
            name='end_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='agentownercontract',
            name='start_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='agentownercontract',
            name='status',
            field=models.CharField(choices=[('active', 'Actif'), ('expired', 'Expire'), ('terminated', 'Resilie')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='end_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='start_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Actif'), ('expired', 'Expire'), ('terminated', 'Resilie')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AddIndex(
            model_name='agentownercontract',
            index=models.Index(fields=['agent', 'status'], name='contracts_a_agent_i_8a0ca6_idx'),
        ),
        migrations.AddIndex(
            model_name='agentownercontract',
            index=models.Index(fields=['owner', 'status'], name='contracts_a_owner_i_f87a4d_idx'),
        ),
        migrations.AddIndex(
            model_name='agentownercontract',
            index=models.Index(fields=['status', 'end_date'], name='contracts_a_status_6cbeb7_idx'),
        ),
        migrations.AddIndex(
            model_name='leasecontract',
            index=models.Index(fields=['tenant', 'status'], name='contracts_l_tenant__a1fa3e_idx'),
        ),
        migrations.AddIndex(
            model_name='leasecontract',
            index=models.Index(fields=['owner', 'status'], name='contracts_l_owner_i_4f7368_idx'),
        ),
        migrations.AddIndex(
            model_name='leasecontract',
            index=models.Index(fields=['agent', 'status'], name='contracts_l_agent_i_a08064_idx'),
        ),
        migrations.AddIndex(
            model_name='leasecontract',
            index=models.Index(fields=['status', 'end_date'], name='contracts_l_status_e7557b_idx'),
        ),
        migrations.AddIndex(
            model_name='leasecontract',
            index=models.Index(fields=['renewal_notified', 'end_date'], name='contracts_l_renewal_f05975_idx'),
        ),
        migrations.AddIndex(
            model_name='leasecontract',
            index=models.Index(fields=['rental_property', 'status'], name='contracts_l_rental__d44b38_idx'),
        ),
    ]
