# Generated by Django 4.2.13 on 2026-08-19 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_agencyinvitation'),
        ('contracts', '0002_alter_agentownercontract_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leasecontract',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lease_contracts', to='agencies.agency'),
        ),
        migrations.AddIndex(
            model_name='leasecontract',
            index=models.Index(fields=['agency', 'status'], name='contracts_l_agency__7e5709_idx'),
        ),
    ]
