# Generated by Django 4.2.13 on 2026-08-20 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0006_alter_agencyinvitation_status'),
        ('contracts', '0004_backfill_leasecontract_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentownercontract',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agent_owner_contracts', to='agencies.agency'),
        ),
    ]
