# Generated by Django 4.2.13 on 2026-06-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('rewarded', 'Recompense')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referrer', 'status'], name='referrals_r_referre_ebbb80_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referred', 'status'], name='referrals_r_referre_282626_idx'),
        ),
    ]
