[pytest]
DJANGO_SETTINGS_MODULE = intelya.settings.test
python_files = tests/test_*.py
python_classes = Test*
python_functions = test_*
asyncio_mode = strict
filterwarnings =
    ignore::django.utils.deprecation.RemovedInDjango51Warning
    ignore::UserWarning:django.core.handlers.base
    ignore::FutureWarning:google.api_core
    ignore::DeprecationWarning:intelya.settings.base
