# Generated by Django 4.2.13 on 2026-06-01 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conversation_type',
            field=models.CharField(choices=[('client_agent', 'Client Agent'), ('agent_owner', 'Agent Proprietaire'), ('owner_tenant', 'Proprietaire Locataire'), ('agent_forum', 'Forum Agents')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='last_message_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='forummessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='forummessage',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='forummessage',
            name='negotiation_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Accepte'), ('refused', 'Refuse')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Texte'), ('image', 'Image'), ('document', 'Document'), ('system', 'Systeme')], default='text', max_length=10),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['conversation_type', 'is_active'], name='messaging_c_convers_6a9ad5_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['is_active', 'last_message_at'], name='messaging_c_is_acti_43e36d_idx'),
        ),
        migrations.AddIndex(
            model_name='forummessage',
            index=models.Index(fields=['sender', 'receiver'], name='messaging_f_sender__bf7ceb_idx'),
        ),
        migrations.AddIndex(
            model_name='forummessage',
            index=models.Index(fields=['sender', 'negotiation_status'], name='messaging_f_sender__029d6e_idx'),
        ),
        migrations.AddIndex(
            model_name='forummessage',
            index=models.Index(fields=['receiver', 'is_read'], name='messaging_f_receive_de75d7_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='messaging_m_convers_7bc91b_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'is_read'], name='messaging_m_convers_211665_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'created_at'], name='messaging_m_sender__277197_idx'),
        ),
    ]
