# Generated by Django 4.2.13 on 2026-05-30 19:36

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('studio', 'Studio'), ('room', 'Chambre'), ('apartment', 'Appartement'), ('villa', 'Villa'), ('duplex', 'Duplex'), ('office', 'Bureau/Local commercial')], max_length=20)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('rented', 'Loué'), ('suspended', 'Suspendu'), ('expired', 'Expiré')], default='available', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_period', models.CharField(choices=[('monthly', 'Mensuel'), ('quarterly', 'Trimestriel'), ('yearly', 'Annuel')], default='monthly', max_length=20)),
                ('min_lease_months', models.IntegerField(default=1)),
                ('bedrooms', models.IntegerField(default=1)),
                ('bathrooms', models.IntegerField(default=1)),
                ('living_rooms', models.IntegerField(default=0)),
                ('kitchens', models.IntegerField(default=0)),
                ('area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('floor', models.IntegerField(default=0)),
                ('total_floors', models.IntegerField(default=1)),
                ('is_furnished', models.BooleanField(default=False)),
                ('has_generator', models.BooleanField(default=False)),
                ('has_borehole', models.BooleanField(default=False)),
                ('has_water_tank', models.BooleanField(default=False)),
                ('has_fence', models.BooleanField(default=False)),
                ('has_security_guard', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_air_conditioning', models.BooleanField(default=False)),
                ('parking_spots', models.IntegerField(default=0)),
                ('full_address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('neighborhood', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('views_count', models.IntegerField(default=0)),
                ('likes_count', models.IntegerField(default=0)),
                ('interested_count', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, limit_choices_to={'role': 'agent'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_properties', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bien Immobilier',
                'verbose_name_plural': 'Biens Immobiliers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='properties/videos/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='properties/photos/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('is_cover', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='properties.property')),
            ],
            options={
                'verbose_name': 'Photo',
                'ordering': ['order', '-is_cover'],
            },
        ),
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_file', models.FileField(upload_to='properties/plans/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='floor_plan', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='properties.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Like',
                'unique_together': {('property', 'user')},
            },
        ),
    ]
