# Generated by Django 4.2.13 on 2026-05-31 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='available_from',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='has_borehole',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='has_generator',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='has_parking',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_furnished',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='neighborhood',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('studio', 'Studio'), ('room', 'Chambre'), ('apartment', 'Appartement'), ('villa', 'Villa'), ('duplex', 'Duplex'), ('office', 'Bureau/Local commercial')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('rented', 'Loué'), ('suspended', 'Suspendu'), ('expired', 'Expiré')], db_index=True, default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status', 'city'], name='properties__status_103177_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status', 'neighborhood'], name='properties__status_1230ec_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status', 'price'], name='properties__status_800e45_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status', 'property_type'], name='properties__status_e02930_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status', 'bedrooms'], name='properties__status_c142ee_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['agent', 'status'], name='properties__agent_i_e955f5_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['owner', 'status'], name='properties__owner_i_30ec29_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city', 'neighborhood', 'status'], name='properties__city_5ac56a_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['price', 'status', 'bedrooms'], name='properties__price_24eb33_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['has_generator', 'status'], name='properties__has_gen_d6848f_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['has_parking', 'status'], name='properties__has_par_1a7184_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_furnished', 'status'], name='properties__is_furn_c72667_idx'),
        ),
    ]
