# Generated by Django 4.2.13 on 2026-07-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_available_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='panorama_type',
            field=models.CharField(choices=[('equirectangular', 'Equirectangular'), ('cubemap', 'Cubemap')], default='equirectangular', help_text='Type de projection panoramique', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='panorama_url',
            field=models.URLField(blank=True, help_text="URL de l'image 360° (equirectangular ou cubemap)", null=True),
        ),
    ]
