# Generated by Django 4.2.13 on 2026-05-31 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('owner_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('late', 'En retard'), ('disputed', 'Contesté')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('mtn', 'MTN Mobile Money'), ('orange', 'Orange Money'), ('bank', 'Virement bancaire'), ('cash', 'Espèces')], max_length=20, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('due_date', models.DateField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by_agent', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('alert_sent_minus5', models.BooleanField(default=False)),
                ('alert_sent_plus3', models.BooleanField(default=False)),
                ('alert_sent_plus7', models.BooleanField(default=False)),
                ('alert_sent_plus15', models.BooleanField(default=False)),
                ('alert_sent_plus30', models.BooleanField(default=False)),
                ('receipt_pdf', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('period_month', models.IntegerField()),
                ('period_year', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_payments', to='contracts.leasecontract')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_payments_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement de loyer',
                'ordering': ['-due_date'],
                'unique_together': {('lease', 'period_month', 'period_year')},
            },
        ),
        migrations.CreateModel(
            name='DebtRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_owed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('action_taken', models.CharField(blank=True, choices=[('extend', 'Prolonger'), ('claim', 'Réclamer'), ('blocked', 'Bloqué'), ('resolved', 'Résolu')], max_length=20, null=True)),
                ('new_due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_debts', to=settings.AUTH_USER_MODEL)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='contracts.leasecontract')),
                ('rent_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_records', to='leases.rentpayment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dette locataire',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('maintenance', 'Maintenance / Réparation'), ('payment', 'Problème de paiement'), ('neighbor', 'Problème de voisinage'), ('security', 'Problème de sécurité'), ('water', 'Eau / Électricité'), ('other', 'Autre')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Ouverte'), ('in_progress', 'En cours'), ('resolved', 'Résolue'), ('escalated', 'Escaladée admin')], default='open', max_length=20)),
                ('resolution_note', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_assigned', to=settings.AUTH_USER_MODEL)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='contracts.leasecontract')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_filed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plainte',
                'ordering': ['-created_at'],
            },
        ),
    ]
