# Generated by Django 4.2.13 on 2026-06-01 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('maintenance', 'Maintenance / Reparation'), ('payment', 'Probleme de paiement'), ('neighbor', 'Probleme de voisinage'), ('security', 'Probleme de securite'), ('water', 'Eau / Electricite'), ('other', 'Autre')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('open', 'Ouverte'), ('in_progress', 'En cours'), ('resolved', 'Resolue'), ('escalated', 'Escaladee admin')], db_index=True, default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='debtrecord',
            name='action_taken',
            field=models.CharField(blank=True, choices=[('extend', 'Prolonger'), ('claim', 'Reclamer'), ('blocked', 'Bloque'), ('resolved', 'Resolu')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='debtrecord',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_debts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rentpayment',
            name='due_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='rentpayment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('mtn', 'MTN Mobile Money'), ('orange', 'Orange Money'), ('bank', 'Virement bancaire'), ('cash', 'Especes')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rentpayment',
            name='payment_reference',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rentpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('paid', 'Paye'), ('late', 'En retard'), ('disputed', 'Conteste')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['lease', 'status'], name='leases_comp_lease_i_0a537b_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['tenant', 'status'], name='leases_comp_tenant__ac3d6a_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['assigned_to', 'status'], name='leases_comp_assigne_e510af_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['status', 'created_at'], name='leases_comp_status_cbb488_idx'),
        ),
        migrations.AddIndex(
            model_name='debtrecord',
            index=models.Index(fields=['tenant', 'action_taken'], name='leases_debt_tenant__8bfdf5_idx'),
        ),
        migrations.AddIndex(
            model_name='debtrecord',
            index=models.Index(fields=['agent', 'action_taken'], name='leases_debt_agent_i_44874d_idx'),
        ),
        migrations.AddIndex(
            model_name='debtrecord',
            index=models.Index(fields=['lease', 'action_taken'], name='leases_debt_lease_i_8c9d5b_idx'),
        ),
        migrations.AddIndex(
            model_name='rentpayment',
            index=models.Index(fields=['tenant', 'status'], name='leases_rent_tenant__110f36_idx'),
        ),
        migrations.AddIndex(
            model_name='rentpayment',
            index=models.Index(fields=['lease', 'status'], name='leases_rent_lease_i_b138ee_idx'),
        ),
        migrations.AddIndex(
            model_name='rentpayment',
            index=models.Index(fields=['status', 'due_date'], name='leases_rent_status_a66496_idx'),
        ),
        migrations.AddIndex(
            model_name='rentpayment',
            index=models.Index(fields=['due_date', 'alert_sent_minus5'], name='leases_rent_due_dat_8a053d_idx'),
        ),
        migrations.AddIndex(
            model_name='rentpayment',
            index=models.Index(fields=['due_date', 'alert_sent_plus3'], name='leases_rent_due_dat_7241aa_idx'),
        ),
        migrations.AddIndex(
            model_name='rentpayment',
            index=models.Index(fields=['due_date', 'alert_sent_plus7'], name='leases_rent_due_dat_760e62_idx'),
        ),
        migrations.AddIndex(
            model_name='rentpayment',
            index=models.Index(fields=['due_date', 'alert_sent_plus30'], name='leases_rent_due_dat_9e126c_idx'),
        ),
    ]
