# Generated by Django 4.2.13 on 2026-08-19 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_agencyinvitation'),
        ('leases', '0002_alter_complaint_category_alter_complaint_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='agencies.agency'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['agency', 'status'], name='leases_comp_agency__92c529_idx'),
        ),
    ]
