# Generated by Django 4.2.13 on 2026-08-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0004_backfill_complaint_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentpayment',
            name='agency_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
