# Generated by Django 4.2.13 on 2026-05-31 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrow',
            name='release_after',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='escrow',
            name='status',
            field=models.CharField(choices=[('held', 'Bloque'), ('released', 'Libere'), ('refunded', 'Rembourse')], db_index=True, default='held', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='external_reference',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('mtn', 'MTN Mobile Money'), ('orange', 'Orange Money'), ('bank', 'Compte bancaire'), ('cash', 'Especes')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='related_lease_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='related_visit_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Complete'), ('failed', 'Echoue'), ('refunded', 'Rembourse'), ('cancelled', 'Annule')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('visit_fee', 'Frais de visite'), ('rent', 'Loyer'), ('commission', 'Commission agent'), ('deposit', 'Caution'), ('boost', 'Boost agent'), ('refund', 'Remboursement')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='escrow',
            index=models.Index(fields=['status', 'release_after'], name='payments_es_status_888af7_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['payer', 'status'], name='payments_tr_payer_i_9fe630_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['receiver', 'status'], name='payments_tr_receive_831247_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'transaction_type'], name='payments_tr_status_910420_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'created_at'], name='payments_tr_status_e3597b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['payment_method', 'status'], name='payments_tr_payment_b4fca5_idx'),
        ),
    ]
