# Generated by Django 4.2.13 on 2026-06-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_escrow_release_after_alter_escrow_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
