# Generated by Django 4.2.13 on 2026-08-20 00:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0003_agency_bank_account_number_agency_bank_name_and_more'),
        ('payments', '0003_transaction_idempotency_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSplitEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Reussi'), ('failed', 'Echoue')], db_index=True, default='pending', max_length=20)),
                ('disbursed_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_split_entries', to='agencies.agency')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_entries', to='payments.transaction')),
            ],
            options={
                'verbose_name': 'Repartition de Commission',
                'verbose_name_plural': 'Repartitions de Commission',
                'indexes': [models.Index(fields=['agency', 'status'], name='payments_pa_agency__aa7a35_idx'), models.Index(fields=['transaction'], name='payments_pa_transac_c10674_idx')],
            },
        ),
    ]
