# Generated by Django 4.2.13 on 2026-08-20 08:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paymentsplitentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentFeeTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_rent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Palier de Frais Loyer',
                'verbose_name_plural': 'Paliers de Frais Loyer',
                'ordering': ['min_rent'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='agency_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Part figee du frais fixe de loyer revenant a l'agence, calculee a l'initiation.", max_digits=10),
        ),
    ]
