# Generated by Django 4.2.13 on 2026-08-19 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptee'), ('declined', 'Refusee'), ('cancelled', 'Annulee')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='agencies.agency')),
                ('invited_by', models.ForeignKey(limit_choices_to={'role': 'agent'}, on_delete=django.db.models.deletion.CASCADE, related_name='sent_agency_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(limit_choices_to={'role': 'agent'}, on_delete=django.db.models.deletion.CASCADE, related_name='agency_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invitation Agence',
                'verbose_name_plural': 'Invitations Agence',
                'indexes': [models.Index(fields=['invited_user', 'status'], name='agencies_ag_invited_c0fd70_idx'), models.Index(fields=['agency', 'status'], name='agencies_ag_agency__314033_idx')],
            },
        ),
    ]
