# Generated by Django 4.2.13 on 2026-08-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0003_agency_bank_account_number_agency_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='disputes_confirmed_against',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agency',
            name='reliability_score',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name='agency',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
