# Generated by Django 4.2.13 on 2026-08-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0005_backfill_agency_reputation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyinvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptee'), ('declined', 'Refusee'), ('cancelled', 'Annulee'), ('expired', 'Expiree')], db_index=True, default='pending', max_length=20),
        ),
    ]
