# Generated by Django 4.2.13 on 2026-08-19 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0003_alter_property_owner'),
        ('agencies', '0002_agencyinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_agency_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('property_agency_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('proposed', 'Proposee'), ('accepted', 'Acceptee'), ('rejected', 'Refusee'), ('cancelled', 'Annulee')], db_index=True, default='proposed', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['client', 'tenant']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaborations', to=settings.AUTH_USER_MODEL)),
                ('client_agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collaborations_as_client_agency', to='agencies.agency')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaborations_initiated', to=settings.AUTH_USER_MODEL)),
                ('last_proposed_by_agency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='agencies.agency')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to='properties.property')),
                ('property_agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collaborations_as_property_agency', to='agencies.agency')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaborations_responded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Collaboration',
                'verbose_name_plural': 'Collaborations',
            },
        ),
        migrations.CreateModel(
            name='CollaborationProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_agency_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('property_agency_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collaboration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='network.collaboration')),
                ('proposed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proposed_by_agency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agencies.agency')),
            ],
            options={
                'verbose_name': 'Proposition de Collaboration',
                'verbose_name_plural': 'Propositions de Collaboration',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='collaboration',
            index=models.Index(fields=['client_agency', 'status'], name='network_col_client__24a5b9_idx'),
        ),
        migrations.AddIndex(
            model_name='collaboration',
            index=models.Index(fields=['property_agency', 'status'], name='network_col_propert_f710e9_idx'),
        ),
        migrations.AddIndex(
            model_name='collaboration',
            index=models.Index(fields=['property', 'status'], name='network_col_propert_0998ec_idx'),
        ),
    ]
