# Generated by Django 4.2.13 on 2026-08-20 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboration',
            name='commission_disbursed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='commission_disbursed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
