# Generated by Django 4.2.13 on 2026-08-20 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_blacklist_cni_number_alter_blacklist_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='validation_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
