# Generated by Django 4.2.13 on 2026-05-30 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerAgentRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('terminated', 'Résilié'), ('expired', 'Expiré')], default='active', max_length=20)),
                ('contract_start', models.DateField()),
                ('contract_end', models.DateField(blank=True, null=True)),
                ('termination_reason', models.TextField(blank=True, null=True)),
                ('terminated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(limit_choices_to={'role': 'agent'}, on_delete=django.db.models.deletion.CASCADE, related_name='owner_relations', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='agent_relations', to=settings.AUTH_USER_MODEL)),
                ('terminated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminated_relations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relation Propriétaire-Agent',
            },
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agency_name', models.CharField(blank=True, max_length=200, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('certification_level', models.CharField(choices=[('basic', 'Agent Basique'), ('certified', 'Agent Certifié'), ('premium', 'Agent Premium')], default='basic', max_length=20)),
                ('working_city', models.CharField(max_length=100)),
                ('working_zones', models.JSONField(default=list)),
                ('commission_type', models.CharField(choices=[('percent', 'Pourcentage'), ('fixed', 'Fixe')], default='percent', max_length=10)),
                ('commission_value', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
                ('visit_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('visit_fee_is_free', models.BooleanField(default=True)),
                ('commission_before_rent', models.BooleanField(default=True)),
                ('reliability_score', models.FloatField(default=0.0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('response_rate', models.FloatField(default=0.0)),
                ('total_transactions', models.IntegerField(default=0)),
                ('total_clients', models.IntegerField(default=0)),
                ('total_properties', models.IntegerField(default=0)),
                ('tax_certificate', models.FileField(blank=True, null=True, upload_to='agents/docs/')),
                ('professional_license', models.FileField(blank=True, null=True, upload_to='agents/docs/')),
                ('office_photo', models.ImageField(blank=True, null=True, upload_to='agents/office/')),
                ('rcc_number', models.CharField(blank=True, max_length=100, null=True)),
                ('max_properties', models.IntegerField(default=20)),
                ('debt_grace_days', models.IntegerField(default=7)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('mtn_momo_number', models.CharField(blank=True, max_length=20, null=True)),
                ('orange_money_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Agent',
                'verbose_name_plural': 'Profils Agents',
            },
        ),
        migrations.CreateModel(
            name='ClientAgentRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(limit_choices_to={'role': 'agent'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_relations', to=settings.AUTH_USER_MODEL)),
                ('client', models.OneToOneField(limit_choices_to={'role__in': ['client', 'tenant']}, on_delete=django.db.models.deletion.CASCADE, related_name='agent_relation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relation Client-Agent',
                'unique_together': {('client', 'agent')},
            },
        ),
        migrations.CreateModel(
            name='AgentAvailabilitySlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('agent', models.ForeignKey(limit_choices_to={'role': 'agent'}, on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Créneau Disponibilité',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('agent', 'day_of_week', 'start_time')},
            },
        ),
    ]
