# Generated by Django 4.2.13 on 2026-05-31 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentavailabilityslot',
            options={'ordering': ['day_of_week', 'start_time'], 'verbose_name': 'Creneau Disponibilite'},
        ),
        migrations.AlterModelOptions(
            name='owneragentrelation',
            options={'verbose_name': 'Relation Proprietaire-Agent'},
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='certification_level',
            field=models.CharField(choices=[('basic', 'Agent Basique'), ('certified', 'Agent Certifie'), ('premium', 'Agent Premium')], db_index=True, default='basic', max_length=20),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='reliability_score',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='working_city',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='clientagentrelation',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='owneragentrelation',
            name='status',
            field=models.CharField(choices=[('active', 'Actif'), ('terminated', 'Resilie'), ('expired', 'Expire')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddIndex(
            model_name='agentprofile',
            index=models.Index(fields=['certification_level', 'reliability_score'], name='agents_agen_certifi_67e1fb_idx'),
        ),
        migrations.AddIndex(
            model_name='agentprofile',
            index=models.Index(fields=['working_city', 'certification_level'], name='agents_agen_working_82db11_idx'),
        ),
        migrations.AddIndex(
            model_name='agentprofile',
            index=models.Index(fields=['reliability_score', 'working_city'], name='agents_agen_reliabi_0a4fa7_idx'),
        ),
        migrations.AddIndex(
            model_name='owneragentrelation',
            index=models.Index(fields=['owner', 'status'], name='agents_owne_owner_i_9f5846_idx'),
        ),
        migrations.AddIndex(
            model_name='owneragentrelation',
            index=models.Index(fields=['agent', 'status'], name='agents_owne_agent_i_78f89b_idx'),
        ),
    ]
