# Generated by Django 4.2.13 on 2026-08-19 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
        ('agents', '0002_alter_agentavailabilityslot_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agents', to='agencies.agency'),
        ),
    ]
