# Generated by Django 4.2.13 on 2026-08-19 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_agencyinvitation'),
        ('agents', '0005_agentprofile_agency_notnull'),
    ]

    operations = [
        migrations.AddField(
            model_name='owneragentrelation',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mandates', to='agencies.agency'),
        ),
    ]
