# Generated by Django 4.2.13 on 2026-08-19 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_agencyinvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agents', '0008_owneragentrelation_agency_notnull'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientagentrelation',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_relations', to='agencies.agency'),
        ),
        migrations.AddField(
            model_name='clientagentrelation',
            name='terminated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientagentrelation',
            name='terminated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminated_client_relations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientagentrelation',
            name='termination_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientagentrelation',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role__in': ['client', 'tenant']}, on_delete=django.db.models.deletion.CASCADE, related_name='client_agent_relations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='clientagentrelation',
            index=models.Index(fields=['client', 'is_active'], name='agents_clie_client__0edddd_idx'),
        ),
        migrations.AddIndex(
            model_name='clientagentrelation',
            index=models.Index(fields=['agency', 'is_active'], name='agents_clie_agency__074ed3_idx'),
        ),
    ]
