# Generated by Django 4.2.13 on 2026-05-31 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('abusive', 'Comportement abusif'), ('fake_info', 'Fausse information'), ('fraud', 'Fraude'), ('harassment', 'Harcèlement'), ('inappropriate', 'Contenu inapproprié'), ('other', 'Autre')], max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('reviewed', 'Examiné'), ('action_taken', 'Action prise'), ('dismissed', 'Rejeté')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signalement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dispute_type', models.CharField(choices=[('visit', 'Litige visite'), ('payment', 'Litige paiement'), ('property', 'Litige bien'), ('agent', 'Litige agent'), ('other', 'Autre')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('reviewing', 'En examen'), ('resolved', 'Résolu'), ('closed', 'Fermé')], default='open', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('evidence', models.FileField(blank=True, null=True, upload_to='disputes/evidence/')),
                ('defendant_response', models.TextField(blank=True, null=True)),
                ('defendant_responded_at', models.DateTimeField(blank=True, null=True)),
                ('decision', models.CharField(blank=True, choices=[('claimant_wins', 'Demandeur gagne'), ('defendant_wins', 'Défendeur gagne'), ('compromise', 'Compromis'), ('no_action', 'Aucune action')], max_length=20, null=True)),
                ('decision_note', models.TextField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('related_visit_id', models.UUIDField(blank=True, null=True)),
                ('related_payment_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes_filed', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_decided', to=settings.AUTH_USER_MODEL)),
                ('defendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Litige',
                'ordering': ['-created_at'],
            },
        ),
    ]
