# Generated by Django 4.2.13 on 2026-06-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='related_transaction_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='decision',
            field=models.CharField(blank=True, choices=[('claimant_wins', 'Demandeur gagne'), ('defendant_wins', 'Defendeur gagne'), ('compromise', 'Compromis'), ('no_action', 'Aucune action')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='dispute_type',
            field=models.CharField(choices=[('visit', 'Litige visite'), ('payment', 'Litige paiement'), ('property', 'Litige bien'), ('agent', 'Litige agent'), ('other', 'Autre')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='related_payment_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='related_visit_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='status',
            field=models.CharField(choices=[('open', 'Ouvert'), ('reviewing', 'En examen'), ('resolved', 'Resolu'), ('closed', 'Ferme')], db_index=True, default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('abusive', 'Comportement abusif'), ('fake_info', 'Fausse information'), ('fraud', 'Fraude'), ('harassment', 'Harcelement'), ('inappropriate', 'Contenu inapproprie'), ('other', 'Autre')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('reviewed', 'Examine'), ('action_taken', 'Action prise'), ('dismissed', 'Rejete')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['claimant', 'status'], name='disputes_di_claiman_b876f6_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['defendant', 'status'], name='disputes_di_defenda_88052e_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['status', 'created_at'], name='disputes_di_status_edf3a9_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['dispute_type', 'status'], name='disputes_di_dispute_0efc45_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reported', 'status'], name='disputes_re_reporte_904a59_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reporter', 'status'], name='disputes_re_reporte_09bea4_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', 'created_at'], name='disputes_re_status_2a6f53_idx'),
        ),
    ]
