# Generated by Django 4.2.13 on 2026-08-20 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0003_agency_bank_account_number_agency_bank_name_and_more'),
        ('disputes', '0002_dispute_related_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Deduite automatiquement si le defendeur est un agent rattache a une agence.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes', to='agencies.agency'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['agency', 'status'], name='disputes_di_agency__6fa692_idx'),
        ),
    ]
