# Generated by Django 4.2.13 on 2026-06-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boost',
            name='payment_reference',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='boost',
            name='payment_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
