# Generated by Django 4.2.13 on 2026-05-31 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_rating', models.IntegerField(blank=True, null=True)),
                ('agent_comment', models.TextField(blank=True, null=True)),
                ('property_rating', models.IntegerField(blank=True, null=True)),
                ('property_comment', models.TextField(blank=True, null=True)),
                ('gps_verified', models.BooleanField(default=False)),
                ('visit_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, limit_choices_to={'role': 'agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_reviews', to=settings.AUTH_USER_MODEL)),
                ('rental_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_reviews', to='properties.property')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avis',
                'ordering': ['-created_at'],
            },
        ),
    ]
