# Generated by Django 4.2.13 on 2026-06-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='gps_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='visit_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['agent', 'gps_verified'], name='reviews_rev_agent_i_f5bbb8_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rental_property', 'gps_verified'], name='reviews_rev_rental__6fe77c_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['reviewer', 'created_at'], name='reviews_rev_reviewe_06e3c4_idx'),
        ),
    ]
