# Generated by Django 4.2.13 on 2026-05-31 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('scheduled', 'Programmée'), ('completed', 'Effectuée'), ('cancelled', 'Annulée')], default='pending', max_length=20)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('visit_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_free', models.BooleanField(default=True)),
                ('payment_status', models.CharField(choices=[('not_required', 'Non requis'), ('pending', 'En attente'), ('paid', 'Payé'), ('released', 'Libéré'), ('refunded', 'Remboursé')], default='not_required', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('client_gps_confirmed', models.BooleanField(default=False)),
                ('client_gps_lat', models.FloatField(blank=True, null=True)),
                ('client_gps_lng', models.FloatField(blank=True, null=True)),
                ('client_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('agent_confirmed', models.BooleanField(default=False)),
                ('agent_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.CharField(blank=True, choices=[('client', 'Client'), ('agent', 'Agent'), ('system', 'Système')], max_length=10, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('auto_release_at', models.DateTimeField(blank=True, null=True)),
                ('client_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(limit_choices_to={'role': 'agent'}, on_delete=django.db.models.deletion.CASCADE, related_name='agent_visits', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(limit_choices_to={'role__in': ['client', 'tenant']}, on_delete=django.db.models.deletion.CASCADE, related_name='visit_requests', to=settings.AUTH_USER_MODEL)),
                ('rental_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='properties.property')),
            ],
            options={
                'verbose_name': 'Demande de visite',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('property_rating', models.IntegerField(blank=True, null=True)),
                ('property_comment', models.TextField(blank=True, null=True)),
                ('agent_rating', models.IntegerField(blank=True, null=True)),
                ('agent_comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_reviews', to=settings.AUTH_USER_MODEL)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='visits.visitrequest')),
            ],
            options={
                'verbose_name': 'Avis de visite',
            },
        ),
    ]
