# Generated by Django 4.2.13 on 2026-05-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Demande de visite', 'verbose_name_plural': 'Demandes de visites'},
        ),
        migrations.RenameField(
            model_name='visitrequest',
            old_name='rental_property',
            new_name='visit_property',
        ),
        migrations.AlterField(
            model_name='visitrequest',
            name='auto_release_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitrequest',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('client', 'Client'), ('agent', 'Agent'), ('system', 'Systeme')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='visitrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='visitrequest',
            name='payment_status',
            field=models.CharField(choices=[('not_required', 'Non requis'), ('pending', 'En attente'), ('paid', 'Paye'), ('released', 'Libere'), ('refunded', 'Rembourse')], db_index=True, default='not_required', max_length=20),
        ),
        migrations.AlterField(
            model_name='visitrequest',
            name='scheduled_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('scheduled', 'Programmee'), ('confirmed', 'Confirmee'), ('completed', 'Effectuee'), ('cancelled', 'Annulee'), ('disputed', 'En litige')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='visitrequest',
            index=models.Index(fields=['client', 'status'], name='visits_visi_client__e81ff3_idx'),
        ),
        migrations.AddIndex(
            model_name='visitrequest',
            index=models.Index(fields=['agent', 'status'], name='visits_visi_agent_i_0795ce_idx'),
        ),
        migrations.AddIndex(
            model_name='visitrequest',
            index=models.Index(fields=['visit_property', 'status'], name='visits_visi_visit_p_3dce04_idx'),
        ),
        migrations.AddIndex(
            model_name='visitrequest',
            index=models.Index(fields=['status', 'scheduled_date'], name='visits_visi_status_6911cc_idx'),
        ),
        migrations.AddIndex(
            model_name='visitrequest',
            index=models.Index(fields=['payment_status', 'status'], name='visits_visi_payment_921a6f_idx'),
        ),
        migrations.AddIndex(
            model_name='visitrequest',
            index=models.Index(fields=['auto_release_at', 'payment_status'], name='visits_visi_auto_re_2eb48c_idx'),
        ),
    ]
