# Generated by Django 4.2.13 on 2026-08-20 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_alter_visitrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitrequest',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
