# Generated by Django 4.2.13 on 2026-05-31 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('visit_request', 'Demande de visite'), ('visit_scheduled', 'Visite planifiée'), ('visit_confirmed', 'Visite confirmée'), ('visit_cancelled', 'Visite annulée'), ('rent_reminder', 'Rappel loyer'), ('rent_late', 'Loyer en retard'), ('rent_received', 'Loyer reçu'), ('lease_renewal', 'Renouvellement bail'), ('complaint_new', 'Nouvelle plainte'), ('complaint_resolved', 'Plainte résolue'), ('boost_active', 'Boost activé'), ('boost_expired', 'Boost expiré'), ('referral_reward', 'Bonus parrainage'), ('account_validated', 'Compte validé'), ('payment_success', 'Paiement réussi'), ('payment_failed', 'Paiement échoué'), ('system', 'Système')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('data', models.JSONField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
