# Generated by Django 4.2.13 on 2026-06-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('visit_request', 'Demande de visite'), ('visit_scheduled', 'Visite planifiee'), ('visit_confirmed', 'Visite confirmee'), ('visit_cancelled', 'Visite annulee'), ('rent_reminder', 'Rappel loyer'), ('rent_late', 'Loyer en retard'), ('rent_received', 'Loyer recu'), ('lease_renewal', 'Renouvellement bail'), ('complaint_new', 'Nouvelle plainte'), ('complaint_resolved', 'Plainte resolue'), ('boost_active', 'Boost active'), ('boost_expired', 'Boost expire'), ('referral_reward', 'Bonus parrainage'), ('account_validated', 'Compte valide'), ('payment_success', 'Paiement reussi'), ('payment_failed', 'Paiement echoue'), ('system', 'Systeme')], db_index=True, max_length=30),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'notification_type'], name='notificatio_recipie_028906_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_f39341_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read', 'created_at'], name='notificatio_is_read_3a06ff_idx'),
        ),
    ]
