# Generated by Django 4.2.13 on 2026-08-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('visit_request', 'Demande de visite'), ('visit_scheduled', 'Visite planifiee'), ('visit_confirmed', 'Visite confirmee'), ('visit_cancelled', 'Visite annulee'), ('rent_reminder', 'Rappel loyer'), ('rent_late', 'Loyer en retard'), ('rent_received', 'Loyer recu'), ('lease_renewal', 'Renouvellement bail'), ('complaint_new', 'Nouvelle plainte'), ('complaint_resolved', 'Plainte resolue'), ('boost_active', 'Boost active'), ('boost_expired', 'Boost expire'), ('referral_reward', 'Bonus parrainage'), ('account_validated', 'Compte valide'), ('payment_success', 'Paiement reussi'), ('payment_failed', 'Paiement echoue'), ('agency_invitation', 'Invitation agence'), ('agency_invitation_accepted', 'Invitation acceptee'), ('agency_invitation_declined', 'Invitation refusee'), ('agency_member_removed', "Retire de l'agence"), ('system', 'Systeme')], db_index=True, max_length=30),
        ),
    ]
